#!/usr/bin/env python3

import sys
import threading

try:
	import termuxgui as tg
except ModuleNotFoundError:
	sys.exit("termuxgui module not found. Please install the Termux:GUI python bindings: https://github.com/tareksander/termux-gui-python-bindings")



ret = tg.connect()
if ret == None:
    sys.exit("Could not connect to the plugin")
main, event = ret


def handleEvents():
	global event
	while True:
		msg = tg.__read_msg.__read_msg(event)
		print(json.dumps(msg), file=sys.stderr, flush=True)


def handleOutput():
	global main
	while True:
		msg = tg.__read_msg.__read_msg(main)
		print(json.dumps(msg), flush=True)


eventt = threading.Thread(target=handleEvents,daemon=True)
outt = threading.Thread(target=handleOutput,daemon=True)
eventt.start()
outt.start()


while True:
	tg.__send_msg.__send_msg(main, sys.stdin.readline())

